/**
 * MediaCapsule API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AccountLevel = 0 | 1 | 2 | 3;

export const AccountLevel = {
    Free: 0 as AccountLevel,
    Standard: 1 as AccountLevel,
    Pro: 2 as AccountLevel,
    Enterprise: 3 as AccountLevel
};
