/**
 * MediaCapsule API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AutomaticArchiveMethods = 0 | 1;

export const AutomaticArchiveMethods = {
    None: 0 as AutomaticArchiveMethods,
    Scheduled: 1 as AutomaticArchiveMethods
};
