/**
 * MediaCapsule API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type FileCatalystStorageMethods = 0 | 1 | 2;

export const FileCatalystStorageMethods = {
    Archive: 0 as FileCatalystStorageMethods,
    Online: 1 as FileCatalystStorageMethods,
    Both: 2 as FileCatalystStorageMethods
};
