/**
 * MediaCapsule API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AutomaticArchiveMethods } from './automaticArchiveMethods';


export class StoragePolicy {
    directToArchive?: boolean;
    automaticArchive?: AutomaticArchiveMethods;
    archiveScheduleDays?: number;
    createImageThumbnailsBeforeArchive?: boolean;
    removeFromStorage?: AutomaticArchiveMethods;
    removeFromStorageDays?: number;
}
