/**
 * MediaCapsule API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Notices global warnings
 */
export interface GlobalNotice {
    /**
     * Notice body
     */
    note?: string;
    /**
     * Date/Time message expired
     */
    expiredOn?: Date;

    id: number;

    dateCreated: Date;

    dateModified?: Date;
}
