/**
 * MediaCapsule API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ServiceNotice } from './serviceNotice';


/**
 * User/
 */
export interface ServiceNoticeAcknowledgement {
    /**
     * ServiceNoticeId
     */
    serviceNoticeId?: number;
    serviceNotice?: ServiceNotice;
    /**
     * User Id of acknowledging user
     */
    userId?: number;
    id?: number;
    dateCreated?: Date;
    dateModified?: Date;
}
