/**
 * MediaCapsule API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ServiceNoticeAcknowledgement } from './serviceNoticeAcknowledgement';


/**
 * Service notices for system wide alerts
 */
export interface ServiceNotice {
    /**
     * The body of the notice
     */
    notice?: string;
    /**
     * Notice start date
     */
    startDate?: Date;
    /**
     * Notice expiry date
     */
    endDate?: Date;
    /**
     * Notice assigned to specific user
     */
    userId?: number;
    /**
     * User Acknowledgement for current notice
     */
    serviceNoticeAcknowledgements?: Array<ServiceNoticeAcknowledgement>;
    id?: number;
    dateCreated?: Date;
    dateModified?: Date;

    isDeleted: boolean;

    isSystemNote: boolean;
}
